### ISSUE TITLE
Could there be a Scala version available?

### ISSUE THREAD

**Issue by cosmir17** [akka/alpakka-samples#10]
Could there be a Scala version available?

**Comment by 2m** [comment]
Which connector are you interested in?

Take a look at https://github.com/akka/alpakka/tree/master/doc-examples/src/main/scala where we have smaller but also interesting examples using multiple Alpakka connectors.

Also, if you would be willing to convert one of the samples here to Scala, we would greatly appreciate that.

**Comment by cosmir17** [comment]
@2m  I am interested in the Cassandra & Slick connectors. I don't need it urgently. I am interested.

I am currently using Cakesolution's Akka & Kafka library without Akka stream feature.
https://github.com/cakesolutions/scala-kafka-client

It would be awesome if there is an (Scala) example available in either near or distant future as Akka's primary users are Scala developers.

**Comment by 2m** [comment]
Yea, there can always be improvements and more time spent when it comes to writing more example code.

There is one example in the `doc-examples` project where ti reads from DB using the slick connector: https://github.com/akka/alpakka/blob/master/doc-examples/src/main/scala/elastic/FetchUsingSlickAndStreamIntoElastic.scala

Also, regarding Cassandra connector, there are going to be some changed to the API soon: https://github.com/akka/alpakka/pull/1573 and https://github.com/akka/alpakka/issues/1213

**Comment by cosmir17** [comment]
@2m Looking forward to seeing examples when we have a release version of 1.0.x

**Comment by ennru** [comment]
We now collect and publish examples on the [Alpakka samples](https://akka.io/alpakka-samples/) site.
Not all cover both Scala and Java, though.
