### ISSUE TITLE
Create a site and deploy to ghPages

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-samples#16]
The `alpakka-sample-http-csv-to-kafka` example is capable of creating a site showing step-by-step changes to the example. This could be auto-deployed to ghPages.

**Comment by ennru** [comment]
Deployed the first version to https://akka.io/alpakka-samples/http-csv-to-kafka/
Still needs automation.

**Comment by 2m** [comment]
One idea is to have sbt-site with multiple `Paradox` configuration for every site. That way everything could be generated in a single `makeSite` task invocation.

**Comment by ennru** [comment]
It is alive and works as expected now!
