### ISSUE TITLE
Move Elasticsearch self-contained example from Alpakka Docs

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-samples#20]
### Short description

Elasticsearch self-contained example (https://doc.akka.io/docs/alpakka/current/examples/elasticsearch-samples.html) should be moved to this repository as a step-by-step example (as Kafka example was: https://github.com/akka/alpakka-samples/pull/13).

**Comment by ennru** [comment]
First example moved with #29 and https://github.com/akka/alpakka/pull/1753

**Comment by ennru** [comment]
Next part in #31

**Comment by ennru** [comment]
All available at https://akka.io/alpakka-samples/index.html now.
