### ISSUE TITLE
Akka Kafka Sample Problem

### ISSUE THREAD

**Issue by zaf187** [akka/alpakka-samples#46]
Hi,

When I am trying to run the Kafka Akka sample I am having a problem in this line of code, in line _103_ of _Main.java_;
`.run(actorSystem);`

Here my IDE is saying that it's expecting a _Materializer_, not an _ActorSystem_
![image](https://user-images.githubusercontent.com/4650757/70638316-93afc780-1c30-11ea-9a0b-a34d0ffddcee.png)

Here are the library versions i am using;
![image](https://user-images.githubusercontent.com/4650757/70638066-22701480-1c30-11ea-9a61-3c64cb52ce29.png)

Maybe I have got something wrong?

Thanks

**Comment by ennru** [comment]
The sample uses Akka 2.6 which changed the API there.

**Comment by zaf187** [comment]
which library are you implying needs to be at 2.6?, i now have the configuration;
![image](https://user-images.githubusercontent.com/4650757/70704410-d70a4480-1cc9-11ea-96fa-07d2110f05a9.png)

**Comment by zaf187** [comment]
I have even tried changing the dependencies to this;
![image](https://user-images.githubusercontent.com/4650757/70706012-00789f80-1ccd-11ea-82c7-370980d28ab0.png)

it's still giving the same error

**Comment by zaf187** [comment]
So I finally got it to work by rolling back some of the changes you made, here are the versions I am currently using;
![image](https://user-images.githubusercontent.com/4650757/70710112-6584c300-1cd6-11ea-9324-e3c3c059cd94.png)

I added the `Materializer` back in

**Comment by ennru** [comment]
Make sure to have all main Akka dependencies of the same patch version.
You should have `2.5.27` on all Akka artefacts, sometimes you may need to depend explicitly on Akka modules which are pulled in by a library you use.
Starting with Akka 2.6.0 it won't start until you sort that out.

See https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
